version: 0.0
os: windows
files:
  - source: \builds\
    destination: C:\inetpub\wwwroot\cliente2\api\
  - source: \builds\
    destination: C:\inetpub\wwwroot\cliente3\api\
  - source: \builds\
    destination: C:\inetpub\wwwroot\cliente1\api\
